# Generated by Django 5.1.5 on 2025-02-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_en', models.CharField(max_length=255)),
                ('question_fr', models.CharField(blank=True, max_length=255, null=True)),
                ('question_es', models.CharField(blank=True, max_length=255, null=True)),
                ('answer_en', models.TextField()),
                ('answer_fr', models.TextField(blank=True, null=True)),
                ('answer_es', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
